name: Deploy to Ec2

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-on-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Clone repo and run tests on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          rm -rf springboot-quickstart &&
          git clone https://github.com/${{ github.repository }}.git &&
          cd springboot-quickstart &&
          git checkout ${{ github.ref_name }} &&
          ./mvnw clean test
        "
    - name: Run application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd springboot-quickstart &&
          nohup ./mvnw spring-boot:run > app.log 2>&1 &
        "
    - name: Build JAR on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd springboot-quickstart &&
          ./mvnw package -DskipTests
        "
